title: Amanze Emeka
description: DevOps Engineer & Instructor
site_title: '@abhn - Amanze Emeka'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: amanzeedward@yahoo.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
